# Tell UniTime to load our custom stylesheet on top of all pages
tmtbl.custom.css=css/uj-custom.css

# Set the default locale to Arabic
# unitime.locale=ar

# ==========================================
# UJ LOCALIZATION & RTL FORCING
# ==========================================
# Set the default application language to Arabic
unitime.locale.default=ar